### ISSUE TITLE
Fix issues related to documentation in readmes (readme.md, docs/install.md)

### ISSUE THREAD

**Issue by ishubham21** [llaske/sugarizer-server#289]
1. Under the section https://github.com/llaske/sugarizer-server/blob/master/docs/install.md#run-sugarizer-using-docker we need to write `sudo` before cURL and chmod commands because they are attempting to modify files in the root directory and need permissions. 
 2. Under the section https://github.com/llaske/sugarizer-server/blob/master/docs/install.md#run-sugarizer-on-linux, under "Install Sugarizer-server and sugarizer" sub-section, we need to update the command `cd /home/root/sugarizer-server` to `cd sugarizer-server` since the user is already in `/home/root` directory
 3. For some systems, `/home/root` directory may not be present and need to be made, so we need to add the command `cd /home && sudo mkdir root`
 4.  In the [main readme.md](https://github.com/llaske/sugarizer-server/blob/master/README.md) file, the instructions under https://github.com/llaske/sugarizer-server#running-sugarizer-server are not clear. It should also include a sentence `To access dashboard, follow the link - http://127.0.0.1:8080/`.

**Comment by NikhilM98** [comment]
Yeah, you're right. Some instructions are ambiguous and the instructions for Mac and Linux are not consistent. 

> Under the section https://github.com/llaske/sugarizer-server/blob/master/docs/install.md#run-sugarizer-using-docker we need to write sudo before cURL and chmod commands because they are attempting to modify files in the root directory and need permissions.

In some parts of the documentation, it's assumed that the user is running as root user while in other parts, the user is non-root user. It'll be nice to make it consistent.


> Under the section https://github.com/llaske/sugarizer-server/blob/master/docs/install.md#run-sugarizer-on-linux, under "Install Sugarizer-server and sugarizer" sub-section, we need to update the command cd /home/root/sugarizer-server to cd sugarizer-server since the user is already in /home/root directory

It does not matters if the path is relative or fixed, both are correct. However, it'll be nice to make it consistent over the docs.

> For some systems, `/home/root` directory may not be present and need to be made, so we need to add the command `cd /home && sudo mkdir root`

Yeah, that's right. It's not good to assume that this path exists. Instead of forcing the user to install the Sugarizer stack at a fixed path, it'll be nice to make the instructions flexible like this:
```
git clone https://github.com/llaske/sugarizer
git clone https://github.com/llaske/sugarizer-server
cd sugarizer-server
npm install
```
```
mongod --fork --port 27018 --logpath ~/mongo.log
nohup node sugarizer.js > ~/sugarizer.log &
```
(It's just a quick suggestion, I have not tested these commands)

> It should also include a sentence To access dashboard, follow the link - http://127.0.0.1:8080/.

It's true that the instructions are not clear, but the path can be different depending on the `.ini` file which stores the environment variables. Maybe we can add a comment pointing to the default path, and let the users know that the path can be modified.


@llaske what are your thoughts about this?

**Comment by NikhilM98** [comment]
Great! However, I'd like to know @llaske's opinion on using `sudo` in the documentation.

**Comment by llaske** [comment]
I think it's better to mention `sudo` for Linux and no mention it on MacOS because, from my experience, it's not need.
BTW we can't cover all possible case and to install Sugarizer Server, the user need a minimum of admin skill.
It will be too long and too time consuming to maintain a documentation for dummies.

**Comment by NikhilM98** [comment]
>BTW we can't cover all possible case and to install Sugarizer Server, the user need a minimum of admin skill.
It will be too long and too time consuming to maintain a documentation for dummies.

Yeah, that makes sense. However, the current instruction to install the stack on the "home/root" directory is a bit misleading.
It'll be nice to make it short and flexible.

Something like this:
```
sudo apt-get install git
git clone https://github.com/llaske/sugarizer
git clone https://github.com/llaske/sugarizer-server
cd sugarizer-server
// npm install should not require sudo either
npm install
```

After that:
```
sudo mongod --fork --port 27018 --logpath ~/mongo.log
// It can be a security risk to run sugarizer.js with root permission, so it's better to run it without sudo
nohup node sugarizer.js > ~/sugarizer.log &
```

**Comment by llaske** [comment]
Closed due to lack of activity.
