### ISSUE TITLE
Making Assignment Page UI 

### ISSUE THREAD

**Issue by dhwaj1902** [llaske/sugarizer-server#299]
I would like to make Assignment Page UI and add assignments tab in the sidebar as shown:
![image](https://user-images.githubusercontent.com/57860123/158026895-0a6b7447-69e6-4653-9c89-6e9a94535a46.png)

**Comment by NikhilM98** [comment]
You're welcome to make a prototype for the Sugarizer Assignment project on your fork. It's also possible to reference the prototype on your proposal to make it stronger.

However, it will be unfair to other candidates if you create a PR on this repository for this feature before the actual GSoC period begins.

Also, this issue is irreverent since it does not addresses any bug or issue with Sugarizer Server.

**Comment by Shreyas-SAS** [comment]
> You're welcome to make a prototype for the Sugarizer Assignment project on your fork. It's also possible to reference the prototype on your proposal to make it stronger.

@NikhilM98 sir can I do the same?

**Comment by NikhilM98** [comment]
@Shreyas-SAS there's no reason why a student should not be allowed to create a prototype. It's a good way to showcase that you have the required skills for the project (You don't need permission for that)

Although contributions to Sugarizer Server in form of bug fixes would be of more value at this point for the organization, prototype of the project implementation can be a good indicator of programming skills.
