### ISSUE TITLE
Text-Align : Center for the select element does not work in Safari Browsers

### ISSUE THREAD

**Issue by mayank190801** [llaske/sugarizer-server#350]
This below link tells that this issue is still not fixed in Safari Browser as of yet. It was raised in 2010.

https://bugs.webkit.org/show_bug.cgi?id=40216

<img width="416" alt="Safari Browser" src="https://user-images.githubusercontent.com/54149585/217829042-4390fdaa-6022-4abc-af3b-f2cf0297dc2f.png">

**Comment by mayank190801** [comment]
I have couple of ideas for fixing this issue  -

1st one 
- We can use direction : rtl , then use custom padding for big and small displays.
- The con of above method is that when we will do custom padding, due to different languages there will be issues with having some extra space on the left.

2nd one 
- Using ul, li rather than select option, and replacing some code and logic from inside.

What does everyone suggest we should do??

**Comment by llaske** [comment]
Thanks for the analysis.
It seems related to Safari only because it works on Chrome.
I'm not in favor of doing anything because:
- It's not a major issue
- Safari is definitively not the most used browser by Sugarizer Server users
- Using `rtl` feature proposed by the workaround you mentioned should not be used in this context

**Comment by mayank190801** [comment]
I totally agree with you. It's not a major issue and can be neglected.
