### ISSUE TITLE
Allow sorting users and classrooms in Dashboard

### ISSUE THREAD

**Issue by ashish0910** [llaske/sugarizer-server#50]
The api provides feature to sort the users as show in documentation written in `api/controller/users.js`

![screenshot 2019-03-03 at 12 45 05 pm](https://user-images.githubusercontent.com/30404493/53692224-3427b000-3db2-11e9-802d-863c7269ce77.png)

but when we run it on browser for +name it gives 

![screenshot 2019-03-03 at 12 46 47 pm](https://user-images.githubusercontent.com/30404493/53692257-7d77ff80-3db2-11e9-9fff-920910bd44d2.png)

and for -name it gives 

![screenshot 2019-03-03 at 12 46 59 pm](https://user-images.githubusercontent.com/30404493/53692274-be701400-3db2-11e9-90d8-fe45d69ac6b6.png)

We are getting the same result for both . Similarly for other parameters for sort we are getting the same result .
I would like to fix this issue and provide sort by column feature on all views in Users/Journal/Activities/Classrooms screen .

**Comment by NikhilM98** [comment]
@ashish0910 I think maintainers are well aware is this issue. I saw this issue on [GSoC idea page](https://github.com/sugarlabs/GSoC/blob/master/Ideas-2019.md#expand-sugarizer-exerciser-activity). 

The sort functionality in the `api/controller` is well written and tested. You can check the `test` folder to find the tests for sorting. The reason you can't sort is because it's hard-coded to sort in specific way:
https://github.com/llaske/sugarizer-server/blob/7d54cf1239929513abcd533362a5e68663870c60/dashboard/controller/activities.js#L24-L27

**Comment by ashish0910** [comment]
Yes @NikhilM98 I Know this . The main idea is to add this feature like sort by date , name etc in the views .
I will start working on it .

**Comment by llaske** [comment]
PR continue on https://github.com/llaske/sugarizer-server/pull/77

**Comment by llaske** [comment]
Fix inhttps://github.com/llaske/sugarizer-server/commit/a5d31937245708b559c3ff24d4fd4f0a5c7a2ab7
