### ISSUE TITLE
users , classroom add route crash 

### ISSUE THREAD

**Issue by ashish0910** [llaske/sugarizer-server#69]
After fetching upstream  the dev branch crashes for `http://127.0.0.1:8080/dashboard/classrooms/add`
and `http://127.0.0.1:8080/dashboard/users/add` routes 

![screenshot 2019-03-07 at 1 02 59 pm](https://user-images.githubusercontent.com/30404493/53939641-b9c09e00-40d9-11e9-8a1f-a5ddcc6118d7.png)

![screenshot 2019-03-07 at 1 05 03 pm](https://user-images.githubusercontent.com/30404493/53940541-f8575800-40db-11e9-9d88-c0bebf87d36d.png)

version - HEAD is now at a56dd9a... Merge pull request #67 from ashish0910/size

I have started working on this issue .

**Comment by NikhilM98** [comment]
@ashish0910 good job finding the issue. It's due to `server` variable being undefined. It can be solved by passing `server: ini.information` while calling `res.render` for those views. I wonder why this issue didn't show up earlier.
I've to modify my restructuring PRs for this error too. While you are at it. Can you fix the typo mentioned in #66 too. I think bugs fixes and restructuring should me done in seperate commits. It will keep the git history clean.

**Comment by llaske** [comment]
Should be solved now. Could you check?

**Comment by ashish0910** [comment]
solved in #71
