### ISSUE TITLE
Add Minification to project

### ISSUE THREAD

**Issue by ashish0910** [llaske/sugarizer-server#90]
Currently project is not using any tool for management of public resources and minification of code as mentioned [here](https://github.com/sugarlabs/GSoC/blob/master/Ideas-2019.md#improve-sugarizer-server-dashboard) . We can use gulp or grunt or some other tool for it . I propose using gulp for it as in 
#80 .

**Comment by NikhilM98** [comment]
If you're comparing bundlers. I'd recommend Webpack. It has more advantages and is more popular than Gulp and Grunt.

To back my statement, here are some blogs where they are compared:
https://da-14.com/blog/gulp-vs-grunt-vs-webpack-comparison-build-tools-task-runners
https://scotch.io/@VitalyKuprenko/grunt-vs-gulp-vs-webpack-an-elaborate-comparison-of-tools

**Comment by ahmedkrmn** [comment]
Totally agree with @NikhilM98.
@ashish0910 thanks for bringing up this issue.

**Comment by SomtochiAma** [comment]
We could change the code to ES6 syntax then use babel to transpile to ES5 if we are using webpack

**Comment by NikhilM98** [comment]
@SomtochiAma agreed

**Comment by Anshuman71** [comment]
@NikhilM98  @SomtochiAma I was wondering too why we are not using ES6 syntax

**Comment by NikhilM98** [comment]
@Anshuman71
At the current point in time, ECMAScript modules are only available as an [experimental feature](https://nodejs.org/api/esm.html) in Node.js and not all browsers support ES6 and higher.

In order to use Node.js in our project, we need to install Babel in our project which can be used to transpile modern ECMAScript code to ES5 code to ensure backward compatibility.

**Comment by Anshuman71** [comment]
@NikhilM98 yes I am using it in my personal projects.

**Comment by llaske** [comment]
I'm not in favor to add complexity to the current development environment without direct benefit.
Using Webpack and Babel will add complexity where today we just need an editing tool and node.js to run and update Sugarizer Server.
Plus, optimizing Dashboard is not a priority because the dashboard is intend to be use by few users (teachers and admin). Not the same thing for Sugarizer App where optimization make sense to offer a better experience to students, specifically on mobile device.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer-server/commit/f21e308c72da5a475333e88f2b0b5757354c5042
